import { useState } from "react";
import { useHistory } from "react-router-dom";

const Create = () => {
    const [title, setTitle] = useState('');
    const [body, setBody] = useState('');
    const [author, setAuthor] = useState('mario');
    const [isPending, setIsPending] = useState(false);
    const history = useHistory(); // object that allows navigation

    const handleSubmit = (e) => {
        e.preventDefault(); //prevents default behavior of form submission which would refresh the page
        const blog = { title, body, author }; //create blog object from state variables (id is auto-generated by json server)
        setIsPending(true);

        fetch('http://localhost:8000/blogs', { //make a POST request to json server
            method: 'POST', // specify method as POST
            headers: { "Content-Type": "application/json" }, //specify that we are sending json data
            body: JSON.stringify(blog) //convert blog object to JSON string
        }).then(() => {
            console.log('new blog added');
            setIsPending(false);
            history.push('/');
        });

        
    }

    return ( 
        <div className="create">
            <h2>Add a New Blog</h2>
            <form onSubmit={handleSubmit}>
                <label>Blog title:</label>
                <input 
                    type="text"
                    required
                    value={title}
                    onChange={(e) => setTitle(e.target.value)} //updates title state variable whenever input field changes
                />
                <label>Blog body:</label>
                <textarea 
                    required
                    value={body}
                    onChange={(e) => setBody(e.target.value)}
                />
                <label>Blog author: </label>
                <select
                    value={author}
                    onChange={(e) => setAuthor(e.target.value)}
                >
                    <option value="mario">mario</option>
                    <option value="yoshi">yoshi</option>
                </select>
                {!isPending && <button>Add blog</button>}
                {isPending && <button disabled>Adding blog...</button>}
            </form>
        </div>
     );
}

export default Create;